# Generated by Django 2.0.9 on 2019-01-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190124_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notification_type',
            new_name='notification_type',
        ),
    ]
